server:
  port: 8080
  servlet:
    context-path: /healthcare

spring:
  application:
    name: gender-healthcare-system
  
  datasource:
    url: jdbc:mysql://localhost:3306/gender_healthcare_db
    username: ${DB_USERNAME:healthcare_user}
    password: ${DB_PASSWORD:healthcare_pass}
    driver-class-name: com.mysql.cj.jdbc.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
  
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
  
  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

app:
  jwt:
    secret: ${JWT_SECRET:healthcare-secret-key-2024}
    expiration: 86400000 # 24 hours
  
  notification:
    scheduler:
      enabled: true
      interval: 60000 # 1 minute

logging:
  level:
    com.healthcare.gender: DEBUG
    org.springframework.security: DEBUG